### PR TITLE
Scalacheck f patch

### PR DESCRIPTION
**Pull request by fedefernandez**
This would look like this in a Scala project, but it's failing locally with a `Caused by: java.lang.ClassNotFoundException: munit.GenericTest` error

I think using `assert(x.success)` is not giving us enough information when the test is failing

### CODE REVIEW

**Comment by fedefernandez** [comment]
@serras @pabloconde FYI

**Comment by serras** [comment]
I think once we figure out how to run them, then we can add more information to `assert`. Maybe the problem is that Scalacheck is built for SBT and we're trying to use Gradle in a non-standard way?

**Comment by serras** [comment]
At the end of the day, if we can publish the library and consume it from a regular SBT project, maybe we're good?

**Comment by fedefernandez** [comment]
Yes, we'll be fine, this applies only to this project. On the other hand, even though we add more information, it would be better to use the standard `check` or similar.

**Comment by fedefernandez** [comment]
I have updated the PR. munit is based on JUnit4, so this allow us to run the tests

**Pull request merged**
