### PR TITLE
Gradle configuration for publishing artifacts

### PR DESCRIPTION
**Pull request by franciscodr**
This pull request adds the required configuration to publish the project's artifacts in Maven.

### CODE REVIEW

**Comment by serras** [comment]
@franciscodr I've pushed a few changes:
- It turns out that for Multiplatform projects you need to apply the Kotest Gradle plug-in,
- Ktor doesn't have a JS version, so I've only added JVM and Native.

**Comment by serras** [comment]
@franciscodr I've pushed a example SBT project to check that everything works fine. Unfortunately, it seems that SBT expects the name of the package to end in `_2.13`, but publication (at least in Maven local) doesn't add the corresponding suffix.

**Comment by serras** [comment]
It seems that a plug-in exists only for this purpose, and it seems to work!

**Comment by franciscodr** [comment]
@serras This pull request is ready for review. I have tested it locally and I'm able to create and close a staging repository in Sonatype. The last step would be releasing and syncing up with Maven Central to have the artifacts available.

**Review by serras — APPROVED** [review]

**Pull request merged**
